# Generated by Django 3.2.9 on 2022-04-20 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_rename_todo_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Статус задачи'),
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 20), verbose_name='Когда выполнить'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.TextField(verbose_name='Название задачи'),
        ),
    ]
