# Generated by Django 3.2.9 on 2022-04-22 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0008_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Когда выполнить'),
        ),
    ]
