# Generated by Django 3.2.9 on 2022-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0009_alter_todo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
